version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 4

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 1
