version: '3.9'
name: cine-ticket-manager

services:
  database:
    image: postgres:15.3
    restart: unless-stopped
    container_name: db-cine-ticket-manager
    environment:
      POSTGRES_DB: cine-ticket-manager-development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  localstack:
    image: localstack/localstack
    restart: unless-stopped
    container_name: aws-cine-ticket-manager
    environment:
      - AWS_ACCESS_KEY_ID=cine-ticket-manager-development
      - AWS_SECRET_ACCESS_KEY=cine-ticket-manager
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_DEFAULT_OUTPUT=json
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3,sqs
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    volumes:
      - ./tmp/localstack:/tmp/localstack
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh

  api:
    container_name: api-cine-ticket-manager
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    working_dir: /app
    command: sh -c "npm run migration:run && npm run start:dev"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - AWS_REGION=us-west-2
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_S3_BUCKET=cine-ticket-manager-development-bucket
      - AWS_ACCESS_KEY_ID=cine-ticket-manager-development
      - AWS_SECRET_ACCESS_KEY=cine-ticket-manager
      - ENV_NAME=development
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_DATABASE=cine-ticket-manager-development
      - JWT_SECRET=cine-ticket-manager
    depends_on:
      - database
      - localstack
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
