name: Build and tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and tests
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ENV_NAME: 'stage'
      DB_HOST: 'database'
      DB_PORT: 5432
      DB_USER: 'postgres'
      DB_PASS: 'postgres'
      DB_DATABASE: 'cine-ticket-manager'

    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: cine-ticket-manager
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npx eslint "{src,apps,libs,test}/**/*.ts"

      - name: Build
        run: npm run build

      - name: Run Unit Tests
        run: npm run test:cov -- --passWithNoTests

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run e2e Tests
        run: npm run test:e2e -- --passWithNoTests
